name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "3.15"
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: sbaerlocher
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          file: alpine/${{ matrix.version }}.Dockerfile
          push: true
          tags: |
            arillso/alpine:${{ matrix.version }}

  publish-debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "10"
          - "11"
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: sbaerlocher
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          file: debian/${{ matrix.version }}.Dockerfile
          push: true
          tags: |
            arillso/debian:${{ matrix.version }}

  publish-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "20.04"
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: sbaerlocher
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          file: ubuntu/${{ matrix.version }}.Dockerfile
          push: true
          tags: |
            arillso/ubuntu:${{ matrix.version }}
